### ISSUE TITLE
[Bug] Compiling error on main branch

### ISSUE THREAD

**Issue by Pablitox26** [iotaledger/identity.rs#524] opened 2021-12-05 22:50 UTC
## Bug description
When compiling the example identity.rs/examples/account/create_did.rs from the main branch, I get the following errors

the function or associated item new exists for struct CurlPBatchHasher <T1B1Buf>, but its trait bounds were not satisfied
the trait bound T1B1Buf: bee_ternary :: raw :: RawEncodingBuf is not satisfied
mismatched types

## Language version
What programming language are you using? Rust or one of the bindings?
Which version of the language are you running?

- Language: Rust
- Version: 1.56.1

## IOTA Identity version
Which version of IOTA Identity are you using?

- Version (version number, commit, or branch): main branch

## Hardware specification
What hardware are you using? (Delete if not relevant)

- Operating system:
- RAM: 16Gb
- Cores: 8
- Device: Acer Predator Helios 300

## Steps To reproduce the bug
Explain how the maintainer can reproduce the bug.

1. identity.rs/examples/account/create_did.rs
2. cargo run

## Expected behaviour
Describe what you expect to happen.
Compile without errors

## Actual behaviour
Describe what actually happens.
I get errors

## Errors
Paste any errors that you see, including logs, errors, or screenshots.

error[E0599]: the function or associated item `new` exists for struct `CurlPBatchHasher<T1B1Buf>`, but its trait bounds were not satisfied
   --> /home/pablo/.cargo/git/checkouts/bee-781893e298f3299f/44bd84b/bee-pow/src/providers/miner.rs:116:55
    |
116 |         let mut hasher = CurlPBatchHasher::<T1B1Buf>::new(HASH_LENGTH);
    |                                                       ^^^ function or associated item cannot be called on `CurlPBatchHasher<T1B1Buf>` due to unsatisfied trait bounds
    |
    
    error[E0277]: the trait bound `T1B1Buf: bee_ternary::raw::RawEncodingBuf` is not satisfied
   --> /home/pablo/.cargo/git/checkouts/bee-781893e298f3299f/44bd84b/bee-pow/src/providers/miner.rs:116:26
    |
116 |         let mut hasher = CurlPBatchHasher::<T1B1Buf>::new(HASH_LENGTH);
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `bee_ternary::raw::RawEncodingBuf` is not implemented for `T1B1Buf`
    |

error[E0308]: mismatched types
  --> /home/pablo/.cargo/git/checkouts/bee-781893e298f3299f/44bd84b/bee-pow/src/score.rs:52:26
   |
52 |         self.curl.digest(self.pow_input.as_slice())
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `bee_ternary::Trits`, found struct `Trits`
   |
   = note: expected reference `&bee_ternary::Trits`
              found reference `&Trits`
   = note: perhaps two different versions of crate `bee_ternary` are being used?

**Comment by cycraig** [comment] 2021-12-06 07:44
Thanks for the bug report.

This is a duplicate of issue #502 which was fixed on the dev branch in PR #503.

We'll see if we can backport the fix from PR #503 to main urgently.

**Comment by JelleMillenaar** [comment] 2021-12-06 09:01
Should be fixed with #525 :)

**Closed by JelleMillenaar** 2021-12-06 09:01 UTC
