### ISSUE TITLE
[Bug] Calls to IOTA network significantly slow down in debug

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#313] opened 2021-07-14 12:42 UTC
## Bug description

Examples and tests seems to massively slow down when Rust is compiled in debug on the `dev` branch, even more so than would be expected from debug mode. This does not occur on the `main` branch (currently commit cbb28b8005938f24f37440e3e88321ac77c729ac).

## Language version

- Language: Rust
- Perhaps noticeable in WASM?
  -  Update: no slowdown was noticeable with WASM due to the `iota-client` not computing proof-of-work locally when the `wasm` feature is enabled, which changed in https://github.com/iotaledger/iota.rs/pull/480.

## IOTA Identity version

- Version (version number, commit, or branch): `dev` branch, commit cb4bd724e51d85eee4be3e067a0159f4cce1abd3 at time of writing

## Steps To reproduce the bug
Explain how the maintainer can reproduce the bug.

1. Run any example in debug mode. E.g.
```
cargo run --example account_basic
```

**Comment by cycraig** [comment] 2021-07-19 11:09
This was resolved incidentally in PR #292 / commit 4e4bd0ecc535c370677719b538a1cf13df3916b7 by @l1h3r.

Specifically, the `iota-client` builder was previously performing proof-of-work locally for each message added to the tangle rather than having one of the nodes on the network do it. The above commit changes this default to remote proof-of-work.

```
const DEFAULT_LOCAL_POW: bool = false;

[...]

impl ClientBuilder {
  /// Creates a new `ClientBuilder`.
  pub fn new() -> Self {
    Self {
      nodeset: false,
      network: Default::default(),
      builder: iota_client::ClientBuilder::new().with_local_pow(DEFAULT_LOCAL_POW),
    }
  }
```

On the dev branch the examples consistently take a few seconds (~5 instead of >25) and do not have excessive CPU usage, which stays below 10% on my local machine compared to 100% for the entire duration before.

**This issue may be closed.**

**Comment by Thoralf-M** [comment] 2021-07-19 11:32
Local PoW is very slow in debug mode, but that's not a bug

**Comment by cycraig** [comment] 2021-07-19 12:48
Yup, there was just some confusion as to why the examples noticeably slowed down between the `dev` and `main` branches here. 

It was due to a change in `identity-iota`: previously the local proof-of-work option in `iota-client` was turned off by default since the `"wasm"` feature was always enabled, which changed recently.

Before (`main` branch):
```
[features]
# default = ["iota-client/async", "iota-client/futures", "iota-client/tokio"]
default = ["iota-client/wasm"]

# Enables Web Assembly support
wasm = ["iota-client/wasm"]
```

After commit 2ebba4ba46e78b80bf8fe96eb707f09af2fcd3f3:
```
[features]
default = ["async"]

# Enables async runtime support (Tokio)
async = ["iota-client/async"]

# Enables Web Assembly support
wasm = ["iota-client/wasm"]
```

**Closed** 2021-07-19 15:12 UTC
Labels: Bug
